layout_spectrum: 0
typography_spectrum: 0.6235231
color:
  saturation: 0.6185729
  lightness: 0.8711945
  brandStrength: 0.7546549
  rhythmicContrast: 0.1754188
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Papacreative
