name: Papacreative
favicon: null
layout_spectrum: 0.53041
typography_spectrum: 0.31998
title: Papa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eae9e5'
    - '#4f99d3'
    - '#3a6f00'
    - '#97aa00'
  brandStrength: 0.25
  lightness: 0.8711945
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
